### ISSUE TITLE
Convert build/release process from TravisCI to GithubActions

### ISSUE THREAD

**Issue by adamkingit** [razee-io/RemoteResource#161]
TravisCI infrastructure is no longer able to build razee-io repositories. Convert to using Github actions.

We have 2 types of actions.
- Build when code is pushed to any branch
- Build and publish artifacts when a branch is tagged or a release is created

When code is pushed to any branch
- All testing, linting should be performed
- Docker image should be built

The following artifacts should result after a new pre-release is created
- Docker image uploaded to quay.io

The following artifacts should result after a new full release is created
- Docker image uploaded to quay.io
- Kubernetes resources associated with the image should be published in the new Github release in the repo
- NPM module containing all of the node code should be uploaded to npmjs.org

Notes based on contents of the existing `.travis.yml` file:
- Execute the "script:" statements whenever a commit is pushed to a branch
- Execute the "script:" statements whenever aPR is submitted, failing the check if the script steps fail
- Push the container image to quay.io on prerelease or release 
- Publish a GitHub release containing the YAML on prerelease or release 
- Publish the npm module to npmjs.org on release

**Comment by tasneem067** [comment]
https://github.com/tasneem067/RemoteResource/tree/master/.github
